// Auto-generated by audit_site — re-run with --mode data to refresh.

/** All crawled products with price as a plain number (currency symbol stripped). */
export const PRODUCTS = [
  { id: 1,  name: "Blue Top",                                    price: 500,  category: "" },
  { id: 2,  name: "Men Tshirt",                                  price: 400,  category: "" },
  { id: 3,  name: "Sleeveless Dress",                            price: 1000, category: "" },
  { id: 4,  name: "Stylish Dress",                               price: 1500, category: "" },
  { id: 5,  name: "Winter Top",                                  price: 600,  category: "" },
  { id: 6,  name: "Summer White Top",                            price: 400,  category: "" },
  { id: 7,  name: "Madame Top For Women",                        price: 1000, category: "" },
  { id: 8,  name: "Fancy Green Top",                             price: 700,  category: "" },
  { id: 11, name: "Sleeves Printed Top - White",                 price: 499,  category: "" },
  { id: 12, name: "Half Sleeves Top Schiffli Detailing - Pink",  price: 359,  category: "" },
  { id: 13, name: "Frozen Tops For Kids",                        price: 278,  category: "" },
  { id: 14, name: "Full Sleeves Top Cherry - Pink",              price: 679,  category: "" },
  { id: 15, name: "Printed Off Shoulder Top - White",            price: 315,  category: "" },
  { id: 16, name: "Sleeves Top and Short - Blue & Pink",         price: 478,  category: "" },
  { id: 18, name: "Little Girls Mr. Panda Shirt",               price: 1200, category: "" },
] as const;

/** Top-level navigation categories available on the site. */
export const CATEGORIES = ["Women", "Men", "Kids"] as const;

/** Maps each top-level category to its list of subcategories. */
export const SUBCATEGORIES: Record<string, readonly string[]> = {
  Women: ["Dress", "Tops", "Saree"],
  Men:   ["Tshirts", "Jeans"],
  Kids:  ["Dress", "Tops & Shirts"],
} as const;

/**
 * Search term fixtures used to exercise the site's search feature.
 * - valid:   terms drawn from real product names that should return ≥1 result.
 * - invalid: nonsense strings that must return zero results.
 * - partial: 2–3 character prefixes of product names that should match multiple results.
 */
export const SEARCH = {
  valid:   ["Blue", "Tshirt", "Sleeveless", "Dress", "Frozen"],
  invalid: ["xyznotfound123", "zzzzaaa", "!@#$%", "qqqqqxxx"],
  partial: ["Sle", "Top", "Win"],
} as const;

/**
 * Realistic but obviously fake user fixture for registration and checkout flows.
 * email is a function so each call produces a unique address — safe for parallel runs.
 */
export const TEST_USER = {
  /** Generates a unique e-mail on every call via timestamp + random suffix. */
  email:     () => `qa_${Date.now()}_${Math.random().toString(36).slice(2, 7)}@testmail.com`,
  password:  "Test@12345!",
  name:      "Qa Tester",
  firstName: "Qa",
  lastName:  "Tester",
  company:   "FakeOrg Ltd.",
  address:   "42 Automation Lane",
  address2:  "Suite 101",
  city:      "Testville",
  state:     "Testshire",
  country:   "United States",
  zipCode:   "00001",
  mobile:    "5550001234",
  dob: {
    day:   "15",
    month: "January",
    year:  "1990",
  },
};

/**
 * Payment card fixtures for checkout payment flows.
 * valid.expiryYear is a getter so it always resolves to two years from now —
 * a hardcoded year would eventually expire and break tests.
 */
export const PAYMENT = {
  valid: {
    name:        "Qa Tester",
    number:      "4111111111111111",
    cvv:         "123",
    expiryMonth: "12",
    get expiryYear(): string {
      return String(new Date().getFullYear() + 2);
    },
  },
};

/**
 * Review / feedback form fixture.
 * email is a fixed string (not a function) because review submissions
 * do not require uniqueness across test runs.
 */
export const REVIEW = {
  name:  "Qa Tester",
  email: "qa.tester.fixed@testmail.com",
  text:  "This is a test review submitted by an automated QA script. Absolutely not a real purchase.",
};