// Auto-generated by audit_site — re-run with --mode data to refresh.

/**
 * All products available on automationexercise.com.
 * Price is stored as a plain number (currency symbol stripped).
 */
export const PRODUCTS = [
  { id: 1,  name: "Blue Top",                                    price: 500,  category: "" },
  { id: 2,  name: "Men Tshirt",                                  price: 400,  category: "" },
  { id: 3,  name: "Sleeveless Dress",                            price: 1000, category: "" },
  { id: 4,  name: "Stylish Dress",                               price: 1500, category: "" },
  { id: 5,  name: "Winter Top",                                  price: 600,  category: "" },
  { id: 6,  name: "Summer White Top",                            price: 400,  category: "" },
  { id: 7,  name: "Madame Top For Women",                        price: 1000, category: "" },
  { id: 8,  name: "Fancy Green Top",                             price: 700,  category: "" },
  { id: 11, name: "Sleeves Printed Top - White",                 price: 499,  category: "" },
  { id: 12, name: "Half Sleeves Top Schiffli Detailing - Pink",  price: 359,  category: "" },
  { id: 13, name: "Frozen Tops For Kids",                        price: 278,  category: "" },
  { id: 14, name: "Full Sleeves Top Cherry - Pink",              price: 679,  category: "" },
  { id: 15, name: "Printed Off Shoulder Top - White",            price: 315,  category: "" },
  { id: 16, name: "Sleeves Top and Short - Blue & Pink",         price: 478,  category: "" },
  { id: 18, name: "Little Girls Mr. Panda Shirt",                price: 1200, category: "" },
] as const;

/**
 * Top-level navigation categories shown on the site.
 */
export const CATEGORIES = ["Women", "Men", "Kids"] as const;

/**
 * Subcategory lists keyed by their parent category name.
 */
export const SUBCATEGORIES: Record<string, readonly string[]> = {
  Women: ["Dress", "Tops", "Saree"],
  Men:   ["Tshirts", "Jeans"],
  Kids:  ["Dress", "Tops & Shirts"],
};

/**
 * Search term fixtures for testing the product search feature.
 *
 * - `valid`   — single real words found in product names; should return ≥1 result.
 * - `invalid` — nonsense strings guaranteed to return zero results.
 * - `partial` — 2-3 character prefixes of product names; should match multiple results.
 */
export const SEARCH = {
  valid:   ["Blue", "Sleeveless", "Tshirt", "Frozen", "Stylish"],
  invalid: ["xyznotfound123", "zzzzaaa", "!@#$%", "qqqqqq99"],
  partial: ["Sle", "Top", "Dre"],
};

/**
 * Realistic but obviously fake user fixture used for registration and checkout flows.
 * `email` is a function so every call produces a unique address.
 */
export const TEST_USER = {
  /** Returns a unique e-mail address on every invocation. */
  email:     () => `qa_${Date.now()}@testmail.com`,
  password:  "Test@1234!",
  name:      "QA Tester",
  firstName: "QA",
  lastName:  "Tester",
  address:   "123 Fake Street, Apt 4B",
  city:      "Testville",
  state:     "Karnataka",
  country:   "India",
  mobile:    "9876543210",
  zipCode:   "560001",
  dob: {
    day:   "15",
    month: "January",
    year:  "1990",
  },
};

/**
 * Payment card fixtures for checkout payment tests.
 *
 * `valid.expiryYear` is a getter that always returns two years from the
 * current date at runtime — it is never a hardcoded year.
 */
export const PAYMENT = {
  valid: {
    name:          "QA Tester",
    number:        "4111111111111111",
    cvv:           "123",
    expiryMonth:   "12",
    /** Always returns (current year + 2) as a string — guaranteed future date. */
    get expiryYear(): string {
      return String(new Date().getFullYear() + 2);
    },
  },
};